erda-project/erda-release

README.md, erda-addons/templates/configmap/configmap.yaml, erda-addons/templates/registry/deployment.yaml, scripts/build_package.sh, scripts/prepare.sh, scripts/push-ext.sh, templates/addons_values.yaml
- update README info and update host network to net mode
- @luobily
=> update README info and update host network to net mode

CONTRIBUTING.md, LICENSE
/kind document
- add apache-2.0 license
- add contributing.md
/assign @sixther-dc 
no
=> add apache-2.0 license

erda-helm/erda/values.yaml
/kind feature
Delete useless configuration of erda value.yaml
/assign @wangzhuzhen
=> Delete useless configuration of erda value.yaml

erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-clusterrole.yaml, erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-clusterrolebinding.yaml, erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-damonset.yaml, erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-serviceaccout.yaml, erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-storageclass.yaml, erda-helm/erda/charts/volume-provisioner/values.yaml, erda-helm/erda/templates/erda-operator-clusterrole.yaml, erda-helm/erda/templates/erda-operator-clusterrolebinding.yaml, erda-helm/erda/templates/erda-operator-deployment.yaml, erda-helm/erda/templates/erda-operator-serviceaccount.yaml, erda-helm/erda/values.yaml
/kind feature
Optimize the helm value structure of erda-operator and volume-provisioner
/assign @wangzhuzhen @iutx
=> Optimize the helm value structure of erda-operator and volume-provisioner

erda-helm/erda/charts/kms/templates/kms-deployment.yaml, erda-helm/erda/charts/kms/values.yaml, erda-helm/erda/charts/registry/templates/registry-deployment.yaml, erda-helm/erda/charts/registry/templates/registry-pvc.yaml, erda-helm/erda/charts/registry/templates/registry-service.yaml, erda-helm/erda/charts/registry/values.yaml, erda-helm/erda/charts/sonar/templates/sonar-configmap.yaml, erda-helm/erda/charts/sonar/templates/sonar-deployment.yaml, erda-helm/erda/charts/sonar/templates/sonar-ingress.yaml, erda-helm/erda/charts/sonar/templates/sonar-service.yaml, erda-helm/erda/charts/sonar/values.yaml, erda-helm/erda/templates/dice-addons-info-configmap.yaml, erda-helm/erda/values.yaml
/kind feature
Optimize the helm value structure (registry、sonar、kms)
/assign @iutx
=> Optimize the helm value structure (registry、sonar、kms)

erda-helm/erda/Chart.yaml
/kind feature
add the maintainers of the helm chart
/assign @iutx
=> add the maintainers of the helm chart

README.md, erda-helm/erda/values.yaml
/kind document
optimize README.md, add install \ uninstall \ configuration
/assign @iutx @wangzhuzhen
=> optimize README.md

erda/erda-base/templates/erda-operator/clusterrole.yaml
/kind bug
Add erda group to cluster role
/assign @Muzry @iutx 
/cherry-pick release/1.0
=> Add erda group to cluster role

erda/erda-addons/templates/mysql/mysql-deployment.yaml
/kind bug
Fix mysql data is not persisted
/assign @iutx @Muzry 
/cherry-pick release/1.0
=> Fix mysql data is not persisted

erda/erda-addons/templates/mysql/mysql-deployment.yaml
/kind bug
Fix mysql data is not persisted
/assign @iutx @wangzhuzhen
=> Release/1.0 Fix mysql data is not persisted

erda-helm/erda/charts/etcd/templates/etcd-demo.yaml, erda-helm/erda/charts/kafka/templates/demo.yaml, erda-helm/erda/charts/mysql/templates/mysql-statefulset.yaml
/kind bug
Fix mysql data is not persisted
/assign @iutx @wangzhuzhen
=> Master: Fix mysql data is not persisted

erda-helm/README.md, erda-helm/erda/charts/volume-provisioner/templates/volume-provisioner-damonset.yaml
/kind document
/kind bug
1. Bugfix: fix errors in file volume-provisoner-daemonset.yaml
2. Add helm  variables descript files
/assign @luobily  @iutx 
/cherry-pick release/1.1
=> bugfix and  add docs 

erda-helm/README.md, erda-helm/erda/Chart.yaml, erda-helm/erda/templates/dice-addons-info-configmap.yaml, erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/templates/erda-operator-deployment.yaml, erda-helm/erda/values.yaml
/kind feature
release 1.3.0 
/assign @wangzhuzhen @luobily 
=> release: 1.3.0

erda-helm/erda/Chart.yaml, erda-helm/erda/values.yaml
/kind release
/assign @luobily @wangzhuzhen 
=> release: 1.3.1

erda-helm/erda/Chart.yaml, erda-helm/erda/templates/erda-cluster-credential-secret.yaml, erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/templates/erda-upgrade-job.yaml, erda-helm/erda/values.yaml, erda-helm/scripts/upgrade_1.4.sh
/kind feature
add erda cluster credential
upgrade 1.4.0
/assign @luobily @wangzhuzhen 
=> feature: add cluster credential

quick-start/quick-start.sh
/kind document
/assign @luobily
=> feature: add quick-start script

erda-helm/erda/Chart.yaml, erda-helm/erda/charts/elasticsearch/templates/statefulset.yaml, erda-helm/erda/templates/aliyun-registry.yaml, erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/values.yaml
/kind feature
/assign @sixther-dc @luobily @Effet 
=> feature: erda 1.5.0

erda-helm/README.md, erda-helm/erda/Chart.yaml, erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/templates/erda-upgrade-job.yaml, erda-helm/erda/values.yaml
/kind feature
/assign @sixther-dc @luobily 
=> release: 2.0.0

erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/values.yaml
/kind feature
/assign @sixther-dc 
=> feat: update 2.0.0 tags and config

quick-start/variables
=> feature: release quick-start 2.0

quick-start/variables
=> fix: fix image tag

quick-start/templates/quick-start.sh.tpl, quick-start/templates/resources/docker-compose.yml.tpl, quick-start/variables
=> feature: update image for quick-start 2.0

quick-start/variables
=> fix: fix ui image

quick-start/templates/resources/nginx.conf, quick-start/variables
/kind feature
fix: update erda image, to fix create project error
=> fix: update erda image

quick-start/variables
/kind feature
/kind bug
/kind polish
/kind document
=> fix: update erda migration image

erda-helm/erda/Chart.yaml, erda-helm/erda/templates/erda-erda.yaml, erda-helm/erda/templates/erda-operator-clusterrole.yaml, erda-helm/erda/values.yaml
/kind feature
release 2.1.0
/assign @your-reviewer
=> feat: erda release 2.1.0

charts/erda/templates/_helpers.tpl, charts/erda/templates/aliyun-registry.yaml, charts/erda/templates/buildkitd-conifgmap.yaml, charts/erda/templates/certgen/job.yaml, charts/erda/templates/dice-addons-info-configmap.yaml, charts/erda/templates/dice-cluster-agent-rbac.yml, charts/erda/templates/dice-cluster-agent-sa.yml, charts/erda/templates/dice-cluster-info-configmap.yaml, charts/erda/templates/erda-erda.yaml, charts/erda/templates/erda-upgrade-job.yaml, charts/erda/templates/regcred-secret.yaml, charts/erda/values.yaml, scripts/tls/etcd/entrypoint.sh
/kind feature
/assign @sixther-dc 
=> feat: erda release 2.2.0

build_package.sh, scripts/storage/nfs.sh
/kind feature
/assign @sixther-dc @wangzhuzhen 
=> feat: optimize build package script

charts/erda/templates/_helpers.tpl
/kind bug
use custom registry or host network will cause ["\"127.0.0.1:5000\""]
/assign @sixther-dc 
=> fix: buildkitd config registry adrees rendor error
